/* * @author alumno Pierre Reyes */
package interfaces;
import clases.conexion;
import javax.swing.JOptionPane;

public class formulario extends javax.swing.JFrame {
   static Integer code_ws=0;
   static String desc_ws="";
   static Integer cant_ws=0;
   static Double pre_ws=0.00;
   static String susp_ws="";
   static String []cadw=new String[20];
   
   /*
    
   create database facturacion
use facturacion
create table productos(
id_pro int primary key,
desc_pro varchar(50),
cant_pro int,
pre_pro double,
susp_pro varchar(30)
)

insert into productos values (0001,'Tv 55" Sony',15,5000.00,'activo')
insert into productos values (0002,'Laptop Asus memo 10"',10,800.00,'activo')
insert into productos values (0003,'Celular Samsung S4 ',30,2500.00,'inactivo')
insert into productos values (0004,'Pañales Huggies',90,30.40,'activo')
insert into productos values (0005,'Pan Bimbo',20,25.60,'inactivo')
 
select*from productos 
   
    */
   
    public formulario() {
        initComponents();
        conexion lib=new conexion();
        for(int j=0;j<lib.i;j++){
            Tabla1.setValueAt(lib.cad1[j], j, 0);
            Tabla1.setValueAt(lib.cad2[j], j, 1);
            Tabla1.setValueAt(lib.cad3[j], j, 2);
            Tabla1.setValueAt(lib.cad4[j], j, 3);
            Tabla1.setValueAt(lib.cad5[j], j, 4);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tcodigo = new javax.swing.JTextField();
        Tdescripcion = new javax.swing.JTextField();
        Tcantidad = new javax.swing.JTextField();
        Tprecio = new javax.swing.JTextField();
        jsuspendido = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORMULARIO DE MATENIMIENTO ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bless.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bless.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CÓDIGO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("DESCRIPCIÓN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("CANTIDAD");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("PRECIO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("SUSPENDIDO");

        Tcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcodigoActionPerformed(evt);
            }
        });

        Tcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcantidadActionPerformed(evt);
            }
        });

        jsuspendido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tprecio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tdescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tcantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jsuspendido, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tcodigo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jsuspendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(35, 35, 35)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Cantidad", "Precio", "Suspendido"
            }
        ));
        jScrollPane1.setViewportView(Tabla1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcodigoActionPerformed
       code_ws=Integer.parseInt(Tcodigo.getText().trim());    
       verificar();
    }//GEN-LAST:event_TcodigoActionPerformed

    private void TcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcantidadActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        code_ws=Integer.parseInt(Tcodigo.getText().trim());
        desc_ws=Tdescripcion.getText().trim();
        cant_ws=Integer.parseInt(Tcantidad.getText().trim());
        pre_ws=Double.parseDouble(Tprecio.getText().trim());
        susp_ws=String.valueOf(jsuspendido.getSelectedItem());
        validar2();
        
        conexion dato=new conexion();
        
        for(int  j=0;j<dato.i;j++)
        {// for
        Tabla1.setValueAt(dato.cad1[j], j,0);   //codigo
        Tabla1.setValueAt(dato.cad2[j], j,1);   // ap
        Tabla1.setValueAt(dato.cad3[j], j,2);  // am
        Tabla1.setValueAt(dato.cad4[j], j,3);  // nom
        Tabla1.setValueAt(dato.cad5[j], j,4);  // nom}
        }
        JOptionPane.showMessageDialog(null, "Registro actualizado correctamente");
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
    code_ws=Integer.parseInt(Tcodigo.getText().trim());
    desc_ws=Tdescripcion.getText().trim();
    cant_ws=Integer.parseInt(Tcantidad.getText().trim());
    pre_ws=Double.parseDouble(Tprecio.getText().trim());
    susp_ws=String.valueOf(jsuspendido.getSelectedItem());
    validar();
    conexion dato=new conexion();
        for(int  j=0;j<dato.i;j++)
        {// for
        Tabla1.setValueAt(dato.cad1[j], j,0);   //codigo
        Tabla1.setValueAt(dato.cad2[j], j,1);   // ap
        Tabla1.setValueAt(dato.cad3[j], j,2);  // am
        Tabla1.setValueAt(dato.cad4[j], j,3);  // nom
         Tabla1.setValueAt(dato.cad5[j], j,4);  // nom}
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        code_ws=Integer.parseInt(Tcodigo.getText().trim());
        validar1();
        conexion dato=new conexion();
        for(int  j=0;j<dato.i;j++)
        {// for
        Tabla1.setValueAt(dato.cad1[j], j,0);   //codigo
        Tabla1.setValueAt(dato.cad2[j], j,1);   // ap
        Tabla1.setValueAt(dato.cad3[j], j,2);  // am
        Tabla1.setValueAt(dato.cad4[j], j,3);  // nom
        Tabla1.setValueAt(dato.cad5[j], j,4);  // nom}
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new formulario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JTextField Tcantidad;
    private javax.swing.JTextField Tcodigo;
    private javax.swing.JTextField Tdescripcion;
    private javax.swing.JTextField Tprecio;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jsuspendido;
    // End of variables declaration//GEN-END:variables
//===================================================
   public void validar2(){
    if(code_ws.equals("")){
        JOptionPane.showMessageDialog(this,
                "Error, codigo sin datos","Validacion de datos",
                JOptionPane.WARNING_MESSAGE);
        Tcodigo.requestFocus();
       
    }else{
        conexion liba=new conexion(code_ws,desc_ws,cant_ws,pre_ws,susp_ws);
        if(liba.i2==1){
                liba.Modificar();
             for(int j=0;j<liba.i;j++){
                Tabla1.setValueAt(cadw[j], j, 0);
                Tabla1.setValueAt(cadw[j], j, 1);
                Tabla1.setValueAt(cadw[j], j, 2);
                Tabla1.setValueAt(cadw[j], j, 3);
            }
             for(int j=0;j<liba.i2;j++){
                Tabla1.setValueAt(liba.cad1[j],j,0);
                Tabla1.setValueAt(liba.cad2[j],j,1);
                Tabla1.setValueAt(liba.cad3[j],j,2);
                Tabla1.setValueAt(liba.cad4[j],j,3);
            }
        }
    }
}
//=======================Modificar========================
    public void validar1(){
    if(code_ws.equals("")){
        JOptionPane.showMessageDialog(this,
                "Error, codigo sin datos","Validacion de datos",
                JOptionPane.WARNING_MESSAGE);
        Tcodigo.requestFocus();
      
   }else{
        conexion liba=new conexion(code_ws,desc_ws,cant_ws,pre_ws,susp_ws);
                if (liba.i2==1){
                    liba.Eliminar();
            for(int j=0;j<liba.i;j++){
               
                Tabla1.setValueAt(cadw[j], j, 0);
                Tabla1.setValueAt(cadw[j], j, 1);
                Tabla1.setValueAt(cadw[j], j, 2);
                Tabla1.setValueAt(cadw[j], j, 3);
               
            }
             conexion lib=new conexion();
             for(int j=0;j<liba.i2;j++){
                Tabla1.setValueAt(liba.cad1[j],j,0);
                Tabla1.setValueAt(liba.cad2[j],j,1);
                Tabla1.setValueAt(liba.cad3[j],j,2);
                Tabla1.setValueAt(liba.cad4[j],j,3);
               
            }
        }
    }
 }
//===================================================
    void validar(){
             if(code_ws.equals("")){
        JOptionPane.showMessageDialog(null,
                                "ERROR.... Codigo sin datos.",
                                "Validacion de datos",
                                JOptionPane.WARNING_MESSAGE);
          Tcodigo.requestFocus();
          
             }
        else {
           conexion dato_2=new conexion(code_ws,desc_ws,cant_ws,pre_ws,susp_ws);
           if(dato_2.i2==1){
            JOptionPane.showMessageDialog(null,
                                "ERROR.... Codigo Ya existe.",
                                "Validacion de datos",
                                JOptionPane.WARNING_MESSAGE);
            Tcodigo.requestFocus();
           
           }
           else{
           dato_2.Adicionar();
            System.out.println("Codigo  -"+code_ws+ "  se grabara");
           }
         }
     }
 //================================================
   public void verificar(){
    if(code_ws.equals("")){
        JOptionPane.showMessageDialog(null,
                "Error, codigo sin datos","Validacion de datos",
                JOptionPane.WARNING_MESSAGE);
        Tcodigo.requestFocus();
        
    }else{
            conexion lib2=new conexion(code_ws);
        
            Tdescripcion.setText(lib2.desc_db);
            Tcantidad.setText(String.valueOf(lib2.cant_db));
            Tprecio.setText(String.valueOf(lib2.prec_db));
            jsuspendido.setSelectedItem(lib2.susp_db);
            
            for(int j=0;j<lib2.i;j++){
                Tabla1.setValueAt(cadw[j], j, 0);
                Tabla1.setValueAt(cadw[j], j, 1);
                Tabla1.setValueAt(cadw[j], j, 2);
                Tabla1.setValueAt(cadw[j], j, 3);
                Tabla1.setValueAt(cadw[j], j, 4);
             
                }
            for(int j=0;j<lib2.i2;j++){
                Tabla1.setValueAt(lib2.cad1[j], j, 0);
                Tabla1.setValueAt(lib2.cad2[j], j, 1);
                Tabla1.setValueAt(lib2.cad3[j], j, 2);
                Tabla1.setValueAt(lib2.cad4[j], j, 3);
                Tabla1.setValueAt(lib2.cad5[j], j, 4);
                        
        }
      }
    }
   //======================================================
    
}
