package interfaces;
public class menu extends javax.swing.JFrame {

    /** Creates new form menu */
    public menu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuManteimiento = new javax.swing.JMenu();
        Mant_Actualizar = new javax.swing.JMenuItem();
        Mant_Eliminar = new javax.swing.JMenuItem();
        Mant_Agregar = new javax.swing.JMenuItem();
        Menu_consultas = new javax.swing.JMenu();
        cons_Codigo = new javax.swing.JMenuItem();
        cons_Total = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuManteimiento.setText("Mantenimiento");

        Mant_Actualizar.setText("Actualizar");
        Mant_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mant_ActualizarActionPerformed(evt);
            }
        });
        menuManteimiento.add(Mant_Actualizar);

        Mant_Eliminar.setText("Eliminar");
        Mant_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mant_EliminarActionPerformed(evt);
            }
        });
        menuManteimiento.add(Mant_Eliminar);

        Mant_Agregar.setText("Agregar");
        menuManteimiento.add(Mant_Agregar);

        jMenuBar1.add(menuManteimiento);

        Menu_consultas.setText("Consultas");

        cons_Codigo.setText("Por codigo");
        cons_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_CodigoActionPerformed(evt);
            }
        });
        Menu_consultas.add(cons_Codigo);

        cons_Total.setText("Total");
        cons_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_TotalActionPerformed(evt);
            }
        });
        Menu_consultas.add(cons_Total);

        jMenuBar1.add(Menu_consultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mant_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mant_ActualizarActionPerformed
       Actualizacion act=new Actualizacion(this,true);
       act.setVisible(true);
    }//GEN-LAST:event_Mant_ActualizarActionPerformed

    private void cons_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_CodigoActionPerformed
        Consulta_codigo cons=new Consulta_codigo(this,true);
        cons.setVisible(true);
    }//GEN-LAST:event_cons_CodigoActionPerformed

    private void cons_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_TotalActionPerformed
        Consulta_Total cont=new Consulta_Total(this,true);
        cont.setVisible(true);
    }//GEN-LAST:event_cons_TotalActionPerformed

    private void Mant_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mant_EliminarActionPerformed
        Eliminacion elim=new Eliminacion(this,true);
        elim.setVisible(true);
    }//GEN-LAST:event_Mant_EliminarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Mant_Actualizar;
    private javax.swing.JMenuItem Mant_Agregar;
    private javax.swing.JMenuItem Mant_Eliminar;
    private javax.swing.JMenu Menu_consultas;
    private javax.swing.JMenuItem cons_Codigo;
    private javax.swing.JMenuItem cons_Total;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuManteimiento;
    // End of variables declaration//GEN-END:variables

}
