/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author alumno
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opc_consultaEmpleados = new javax.swing.JMenuItem();
        ocp_consultaCargos = new javax.swing.JMenuItem();
        ocp_consultaDepartamentos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opc_busqueda1 = new javax.swing.JMenuItem();
        opc_busqueda2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa ABC - Menu principal"));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empresa224.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1366348871_Magnifier2.png"))); // NOI18N
        jMenu1.setText("Consultas");

        opc_consultaEmpleados.setText("Empleados");
        opc_consultaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_consultaEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(opc_consultaEmpleados);

        ocp_consultaCargos.setText("Cargos");
        ocp_consultaCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocp_consultaCargosActionPerformed(evt);
            }
        });
        jMenu1.add(ocp_consultaCargos);

        ocp_consultaDepartamentos.setText("Departamentos");
        ocp_consultaDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocp_consultaDepartamentosActionPerformed(evt);
            }
        });
        jMenu1.add(ocp_consultaDepartamentos);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bless.png"))); // NOI18N
        jMenu2.setText("Bùsquedas");

        opc_busqueda1.setText("Empleados por cargo");
        opc_busqueda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_busqueda1ActionPerformed(evt);
            }
        });
        jMenu2.add(opc_busqueda1);

        opc_busqueda2.setText("Empleado por departamento");
        opc_busqueda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_busqueda2ActionPerformed(evt);
            }
        });
        jMenu2.add(opc_busqueda2);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FBReader.png"))); // NOI18N
        jMenu3.setText("Reportes");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ocp_consultaCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocp_consultaCargosActionPerformed
        Consulta_cargos cCargos = new Consulta_cargos(this, true);
         cCargos.setVisible(true);
    }//GEN-LAST:event_ocp_consultaCargosActionPerformed

    private void opc_consultaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_consultaEmpleadosActionPerformed
        Consulta_Empleados_en_general ceg=new Consulta_Empleados_en_general(this, true);
        ceg.setVisible(true);
       
    }//GEN-LAST:event_opc_consultaEmpleadosActionPerformed

    private void ocp_consultaDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocp_consultaDepartamentosActionPerformed
        Consulta_departamentos cdep=new Consulta_departamentos(this, true);
        cdep.setVisible(true);
    }//GEN-LAST:event_ocp_consultaDepartamentosActionPerformed

    private void opc_busqueda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_busqueda1ActionPerformed
        Busqueda_empleados_cargo bec= new Busqueda_empleados_cargo(this, true);
        bec.setVisible(true);
    }//GEN-LAST:event_opc_busqueda1ActionPerformed

    private void opc_busqueda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_busqueda2ActionPerformed
       busqueda_departamento bdep= new busqueda_departamento(this, true);
        bdep.setVisible(true);
    }//GEN-LAST:event_opc_busqueda2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem ocp_consultaCargos;
    private javax.swing.JMenuItem ocp_consultaDepartamentos;
    private javax.swing.JMenuItem opc_busqueda1;
    private javax.swing.JMenuItem opc_busqueda2;
    private javax.swing.JMenuItem opc_consultaEmpleados;
    // End of variables declaration//GEN-END:variables
}
